version: "3"

services:
  reverse-proxy:
    image: traefik
    command: --api.insecure=true --providers.docker --providers.docker.exposedByDefault=false
    restart: "no"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  cmyktohsl:
    build: cmyktohsl
    restart: "no"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cmyktohsl.rule=PathPrefix(`/cmyktohsl`)"
      - "traefik.http.routers.cmyktohsl.middlewares=cmyktohsl-stripprefix"
      - "traefik.http.services.cmyktohsl.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.cmyktohsl-stripprefix.stripprefix.prefixes=/cmyktohsl"
  
  hextorgb:
    build: hextorgb
    restart: "no"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hextorgb.rule=PathPrefix(`/hextorgb`)"
      - "traefik.http.routers.hextorgb.middlewares=hextorgb-stripprefix"
      - "traefik.http.services.hextorgb.loadbalancer.server.port=3100"
      - "traefik.http.middlewares.hextorgb-stripprefix.stripprefix.prefixes=/hextorgb"
  
  hsltohex:
    build: hsltohex
    restart: "no"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hsltohex.rule=PathPrefix(`/hsltohex`)"
      - "traefik.http.routers.hsltohex.middlewares=hsltohex-stripprefix"
      - "traefik.http.services.hsltohex.loadbalancer.server.port=3200"
      - "traefik.http.middlewares.hsltohex-stripprefix.stripprefix.prefixes=/hsltohex"

  rgbtocmyk:
    build: rgbtocmyk
    restart: "no"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rgbtocmyk.rule=PathPrefix(`/rgbtocmyk`)"
      - "traefik.http.routers.rgbtocmyk.middlewares=rgbtocmyk-stripprefix"
      - "traefik.http.services.rgbtocmyk.loadbalancer.server.port=3300"
      - "traefik.http.middlewares.rgbtocmyk-stripprefix.stripprefix.prefixes=/rgbtocmyk"